# Generated by Django 5.1.4 on 2025-01-13 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0002_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='agotado',
            field=models.BooleanField(default=False),
        ),
    ]
