# Generated by Django 5.1.4 on 2025-01-13 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0003_producto_agotado'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='direccion',
            field=models.CharField(default='Dirección no proporcionada', max_length=500),
        ),
        migrations.AddField(
            model_name='pedido',
            name='metodo_pago',
            field=models.CharField(default='Pago no especificado', max_length=100),
        ),
    ]
