# Generated by Django 5.1.4 on 2025-01-13 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0004_pedido_direccion_pedido_metodo_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='recomendado',
            field=models.BooleanField(default=False),
        ),
    ]
